import { UserMaster, UserRole, Claim, FormField, AccessRule, EmailTemplate, NotificationRule, SystemSettings } from "./types";

export const initialUsers: UserMaster[] = [
  {
    email: "rahul.sales@arvicon.com",
    name: "Rahul Sharma",
    code: "EMP-2026-042",
    designation: "Sales Executive",
    state: "Maharashtra",
    department: "Sales & Marketing",
    supervisorName: "Vikram Singh",
    supervisorEmail: "vikram.head@arvicon.com",
    hrName: "Siddharth Joshi",
    hrEmail: "siddharth.hr@arvicon.com",
    role: UserRole.SALESPERSON,
    active: true
  },
  {
    email: "pooja.manager@arvicon.com",
    name: "Pooja Patel",
    code: "EMP-2026-068",
    designation: "Area Sales Manager",
    state: "Gujarat",
    department: "Sales & Marketing",
    supervisorName: "Vikram Singh",
    supervisorEmail: "vikram.head@arvicon.com",
    hrName: "Siddharth Joshi",
    hrEmail: "siddharth.hr@arvicon.com",
    role: UserRole.EMPLOYEE,
    active: true
  },
  {
    email: "vikram.head@arvicon.com",
    name: "Vikram Singh",
    code: "EMP-2018-012",
    designation: "Regional Sales Head",
    state: "Maharashtra",
    department: "Sales & Marketing",
    supervisorName: "Devansh Mehta",
    supervisorEmail: "devansh.director@arvicon.com",
    hrName: "Siddharth Joshi",
    hrEmail: "siddharth.hr@arvicon.com",
    role: UserRole.SUPERVISOR,
    active: true
  },
  {
    email: "siddharth.hr@arvicon.com",
    name: "Siddharth Joshi",
    code: "EMP-2015-005",
    designation: "HR Lead",
    state: "Gujarat",
    department: "Human Resources",
    supervisorName: "Devansh Mehta",
    supervisorEmail: "devansh.director@arvicon.com",
    hrName: "Devansh Mehta",
    hrEmail: "devansh.director@arvicon.com",
    role: UserRole.HR,
    active: true
  },
  {
    email: "neha.finance@arvicon.com",
    name: "Neha Gupta",
    code: "EMP-2020-009",
    designation: "Sr. Accountant",
    state: "Gujarat",
    department: "Finance & Accounts",
    supervisorName: "Devansh Mehta",
    supervisorEmail: "devansh.director@arvicon.com",
    hrName: "Siddharth Joshi",
    hrEmail: "siddharth.hr@arvicon.com",
    role: UserRole.ACCOUNTS,
    active: true
  },
  {
    email: "devansh.director@arvicon.com",
    name: "Devansh Mehta",
    code: "EMP-2010-001",
    designation: "Global Director",
    state: "Gujarat",
    department: "Management",
    supervisorName: "",
    supervisorEmail: "",
    hrName: "",
    hrEmail: "",
    role: UserRole.SUPER_ADMIN,
    active: true
  }
];

export const initialFormFields: FormField[] = [
  { id: "employeeName", label: "Employee Name", type: "dropdown", section: "Employee Details", required: true, order: 1, autofillFromUserMaster: "name", visibleToEmployee: true, visibleToSupervisor: true, visibleToHR: true, visibleToAccounts: true },
  { id: "employeeCode", label: "Emp Code", type: "text", section: "Employee Details", required: true, order: 2, autofillFromUserMaster: "code", visibleToEmployee: true, visibleToSupervisor: true, visibleToHR: true, visibleToAccounts: true },
  { id: "designation", label: "Designation", type: "text", section: "Employee Details", required: true, order: 3, autofillFromUserMaster: "designation", visibleToEmployee: true, visibleToSupervisor: true, visibleToHR: true, visibleToAccounts: true },
  { id: "state", label: "State", type: "text", section: "Employee Details", required: true, order: 4, autofillFromUserMaster: "state", visibleToEmployee: true, visibleToSupervisor: true, visibleToHR: true, visibleToAccounts: true },
  { id: "department", label: "Department", type: "text", section: "Employee Details", required: true, order: 5, autofillFromUserMaster: "department", visibleToEmployee: true, visibleToSupervisor: true, visibleToHR: true, visibleToAccounts: true },
  { id: "date", label: "Date", type: "date", section: "Claim Details", required: true, order: 6, visibleToEmployee: true, visibleToSupervisor: true, visibleToHR: true, visibleToAccounts: true },
  { id: "poNo", label: "PO No.", type: "text", section: "Claim Details", required: false, order: 7, visibleToEmployee: true, visibleToSupervisor: true, visibleToHR: true, visibleToAccounts: true },
  { id: "particulars", label: "Particulars", type: "textarea", section: "Claim Details", required: true, order: 8, visibleToEmployee: true, visibleToSupervisor: true, visibleToHR: true, visibleToAccounts: true },
  { id: "openingReading", label: "Opening Reading", type: "number", section: "Claim Details", required: true, order: 9, visibleToEmployee: true, visibleToSupervisor: true, visibleToHR: true, visibleToAccounts: true },
  { id: "closingReading", label: "Closing Reading", type: "number", section: "Claim Details", required: true, order: 10, visibleToEmployee: true, visibleToSupervisor: true, visibleToHR: true, visibleToAccounts: true },
  { id: "readingDifference", label: "Reading Difference", type: "calculated", section: "Claim Details", required: false, order: 11, formula: "closing - opening", visibleToEmployee: true, visibleToSupervisor: true, visibleToHR: true, visibleToAccounts: true },
  { id: "ta", label: "T.A. Amount", type: "number", section: "Claim Details", required: true, order: 12, visibleToEmployee: true, visibleToSupervisor: true, visibleToHR: true, visibleToAccounts: true },
  { id: "da", label: "D.A. Amount", type: "number", section: "Claim Details", required: true, order: 13, visibleToEmployee: true, visibleToSupervisor: true, visibleToHR: true, visibleToAccounts: true },
  { id: "hotel", label: "Hotel Charges", type: "number", section: "Claim Details", required: false, order: 14, visibleToEmployee: true, visibleToSupervisor: true, visibleToHR: true, visibleToAccounts: true },
  { id: "mobileExp", label: "Mobile Exp.", type: "number", section: "Claim Details", required: false, order: 15, visibleToEmployee: true, visibleToSupervisor: true, visibleToHR: true, visibleToAccounts: true },
  { id: "otherExp", label: "Other Exp.", type: "number", section: "Claim Details", required: false, order: 16, visibleToEmployee: true, visibleToSupervisor: true, visibleToHR: true, visibleToAccounts: true },
  { id: "grandTotal", label: "Grand Total", type: "calculated", section: "Claim Details", required: false, order: 17, formula: "ta + da + hotel + mobile + other", visibleToEmployee: true, visibleToSupervisor: true, visibleToHR: true, visibleToAccounts: true },
  { id: "dispatchedPoNo", label: "Dispatched PO No.", type: "text", section: "Claim Details", required: false, order: 18, visibleToEmployee: true, visibleToSupervisor: true, visibleToHR: true, visibleToAccounts: true },
  { id: "billUpload", label: "Bill Upload File", type: "file", section: "Claim Details", required: true, order: 19, visibleToEmployee: true, visibleToSupervisor: true, visibleToHR: true, visibleToAccounts: true }
];

export const initialAccessRules: AccessRule[] = [
  { role: UserRole.EMPLOYEE, menuName: "Dashboard", canView: true, canAdd: true, canEdit: false, canDelete: false, canApprove: false, canReject: false, dataVisibilityType: "Own Data Only" },
  { role: UserRole.EMPLOYEE, menuName: "TA/DA Form", canView: true, canAdd: true, canEdit: true, canDelete: false, canApprove: false, canReject: false, dataVisibilityType: "Own Data Only" },
  { role: UserRole.EMPLOYEE, menuName: "Claims List", canView: true, canAdd: false, canEdit: false, canDelete: false, canApprove: false, canReject: false, dataVisibilityType: "Own Data Only" },
  
  { role: UserRole.SALESPERSON, menuName: "Dashboard", canView: true, canAdd: true, canEdit: false, canDelete: false, canApprove: false, canReject: false, dataVisibilityType: "Own Data Only" },
  { role: UserRole.SALESPERSON, menuName: "TA/DA Form", canView: true, canAdd: true, canEdit: true, canDelete: false, canApprove: false, canReject: false, dataVisibilityType: "Own Data Only" },
  { role: UserRole.SALESPERSON, menuName: "Claims List", canView: true, canAdd: false, canEdit: false, canDelete: false, canApprove: false, canReject: false, dataVisibilityType: "Own Data Only" },

  { role: UserRole.SUPERVISOR, menuName: "Dashboard", canView: true, canAdd: false, canEdit: false, canDelete: false, canApprove: false, canReject: false, dataVisibilityType: "Team Data Only" },
  { role: UserRole.SUPERVISOR, menuName: "Approval Panel", canView: true, canAdd: false, canEdit: true, canDelete: false, canApprove: true, canReject: true, dataVisibilityType: "Team Data Only" },
  { role: UserRole.SUPERVISOR, menuName: "Claims List", canView: true, canAdd: false, canEdit: false, canDelete: false, canApprove: false, canReject: false, dataVisibilityType: "Team Data Only" },

  { role: UserRole.HR, menuName: "Dashboard", canView: true, canAdd: false, canEdit: false, canDelete: false, canApprove: false, canReject: false, dataVisibilityType: "All Data" },
  { role: UserRole.HR, menuName: "Approval Panel", canView: true, canAdd: false, canEdit: true, canDelete: false, canApprove: true, canReject: true, dataVisibilityType: "All Data" },
  { role: UserRole.HR, menuName: "Claims List", canView: true, canAdd: false, canEdit: false, canDelete: false, canApprove: false, canReject: false, dataVisibilityType: "All Data" },

  { role: UserRole.ACCOUNTS, menuName: "Dashboard", canView: true, canAdd: false, canEdit: false, canDelete: false, canApprove: false, canReject: false, dataVisibilityType: "All Data" },
  { role: UserRole.ACCOUNTS, menuName: "Accounts Panel", canView: true, canAdd: false, canEdit: true, canDelete: false, canApprove: true, canReject: false, dataVisibilityType: "All Data" },
  { role: UserRole.ACCOUNTS, menuName: "Claims List", canView: true, canAdd: false, canEdit: false, canDelete: false, canApprove: false, canReject: false, dataVisibilityType: "All Data" },

  { role: UserRole.SUPER_ADMIN, menuName: "Dashboard", canView: true, canAdd: true, canEdit: true, canDelete: true, canApprove: true, canReject: true, dataVisibilityType: "All Data" },
  { role: UserRole.SUPER_ADMIN, menuName: "TA/DA Form", canView: true, canAdd: true, canEdit: true, canDelete: true, canApprove: true, canReject: true, dataVisibilityType: "All Data" },
  { role: UserRole.SUPER_ADMIN, menuName: "Claims List", canView: true, canAdd: true, canEdit: true, canDelete: true, canApprove: true, canReject: true, dataVisibilityType: "All Data" },
  { role: UserRole.SUPER_ADMIN, menuName: "Approval Panel", canView: true, canAdd: true, canEdit: true, canDelete: true, canApprove: true, canReject: true, dataVisibilityType: "All Data" },
  { role: UserRole.SUPER_ADMIN, menuName: "Accounts Panel", canView: true, canAdd: true, canEdit: true, canDelete: true, canApprove: true, canReject: true, dataVisibilityType: "All Data" },
  { role: UserRole.SUPER_ADMIN, menuName: "Admin Settings", canView: true, canAdd: true, canEdit: true, canDelete: true, canApprove: true, canReject: true, dataVisibilityType: "All Data" }
];

export const initialEmailTemplates: EmailTemplate[] = [
  {
    mailType: "Employee Submission Confirmation",
    triggerEvent: "On New Submission",
    subject: "Arvicon Claims: Claim Submission Confirmed {{Submission Number}}",
    body: "<p>Hello {{Employee Name}},</p><p>We acknowledge submission of your Travel/Allowance expense claim under number <strong>{{Submission Number}}</strong> amounting to <strong>INR {{Grand Total}}</strong>.</p><p>The status is currently <strong>Pending Supervisor Review</strong>.</p>",
    signature: "<p>Regards,<br>Arvicon Operations Hub</p>",
    footer: "<p style='font-size:11px;color:#94a3b8;'>This is a system-generated notification. Please do not reply directly.</p>"
  },
  {
    mailType: "Supervisor New Claim Notification",
    triggerEvent: "On New Submission",
    subject: "Action Required: Approve Expense Claim {{Submission Number}} - {{Employee Name}}",
    body: "<p>Hello {{Supervisor Name}},</p><p>A new travel reimbursement request is awaiting your authorization:</p><ul><li>Employee: {{Employee Name}} ({{Employee Code}})</li><li>Submission ID: {{Submission Number}}</li><li>Claim Date: {{Date}}</li><li>Total Expense: INR {{Grand Total}}</li></ul><p>Please authorize this expense inside the Supervisor Dashboard.</p>",
    signature: "<p>Best regards,<br>Arvicon HR Portal</p>",
    footer: "<p style='font-size:11px;color:#94a3b8;'>Corporate Travel Audit Division</p>"
  },
  {
    mailType: "HR New Claim Notification",
    triggerEvent: "On Supervisor Approval",
    subject: "Reconcile Request: HR Clearance required for {{Submission Number}}",
    body: "<p>Greetings HR Desk,</p><p>The travel voucher <strong>{{Submission Number}}</strong> submitted by {{Employee Name}} has been approved by Supervisor {{Supervisor Name}} and is now dispatched to HR Desk for final verification of INR {{Grand Total}}.</p>",
    signature: "<p>Automated Systems Group,<br>Arvicon ERP</p>",
    footer: "<p style='font-size:11px;color:#94a3b8;'>Corporate Travel Audit Division</p>"
  },
  {
    mailType: "Employee Approval Notification",
    triggerEvent: "On HR Approval",
    subject: "Arvicon TA/DA: Claim status remains APPROVED for {{Submission Number}}",
    body: "<p>Hello {{Employee Name}},</p><p>Great news! Your Travel expense application <strong>{{Submission Number}}</strong> has been certified by HR and forwarded to Accounts division for payment routing.</p>",
    signature: "<p>Regards,<br>HR Core Operations</p>",
    footer: "<p style='font-size:11px;color:#94a3b8;'>Arvicon Finance Network</p>"
  }
];

export const initialNotificationRules: NotificationRule[] = [
  { mailType: "Employee Submission Confirmation", triggerEvent: "On New Submission", enabled: true, sendToEmployee: true, sendToSupervisor: false, sendToHR: false, sendToAdmin: false, sendToAccounts: false, ccList: "", bccList: "" },
  { mailType: "Supervisor New Claim Notification", triggerEvent: "On New Submission", enabled: true, sendToEmployee: false, sendToSupervisor: true, sendToHR: false, sendToAdmin: false, sendToAccounts: false, ccList: "management.cc@arvicon.com", bccList: "" },
  { mailType: "HR New Claim Notification", triggerEvent: "On Supervisor Approval", enabled: true, sendToEmployee: false, sendToSupervisor: false, sendToHR: true, sendToAdmin: false, sendToAccounts: false, ccList: "", bccList: "" },
  { mailType: "Employee Approval Notification", triggerEvent: "On HR Approval", enabled: true, sendToEmployee: true, sendToSupervisor: false, sendToHR: false, sendToAdmin: false, sendToAccounts: false, ccList: "", bccList: "" }
];

export const initialSystemSettings: SystemSettings = {
  companyName: "Arvicon International",
  logoUrl: "https://images.unsplash.com/photo-1542744094-3a31f103e35f?w=100&q=80",
  financialYear: "2026-2027",
  themeColor: "#0f766e", // teal-700
  driveFolderId: "1zL9QW_TA_DA_Bills_Arvicon",
  instantMailOn: true,
  supervisorReminderCycle: "Every 15 days",
  hrReminderCycle: "Every 15 days",
  accountsSummaryDay: "1st of Month"
};

export const initialClaims: Claim[] = [
  {
    id: "TADA-2026-00001",
    timestamp: "2026-05-15T11:42:00Z",
    employeeName: "Rahul Sharma",
    employeeCode: "EMP-2026-042",
    employeeEmail: "rahul.sales@arvicon.com",
    designation: "Sales Executive",
    state: "Maharashtra",
    department: "Sales & Marketing",
    date: "2026-05-14",
    poNo: "PO-99120",
    particulars: "Client visitation across Mumbai retail outlets for distributor alignment and catalog handover.",
    openingReading: 12420,
    closingReading: 12515,
    readingDifference: 95,
    ta: 950,
    da: 450,
    hotel: 0,
    mobileExp: 150,
    otherExp: 100,
    grandTotal: 1650,
    dispatchedPoNo: "DISP-1142",
    billUploadFileLink: "https://drive.google.com/file/d/1vA5W38Yf_TADA_MumbaiReceipt/view",
    supervisorName: "Vikram Singh",
    supervisorEmail: "vikram.head@arvicon.com",
    supervisorApprovalStatus: "Approved",
    supervisorApprovalDate: "2026-05-16T09:30:00Z",
    supervisorRemarks: "Approved. Travel logs mapped perfectly against distributor plan.",
    hrName: "Siddharth Joshi",
    hrEmail: "siddharth.hr@arvicon.com",
    hrApprovalStatus: "Approved",
    hrApprovalDate: "2026-05-18T14:15:00Z",
    hrRemarks: "Travel limits verified against budget parameters. Clean voucher.",
    accountsPaymentStatus: "Paid",
    paymentDate: "2026-05-20",
    accountsRemarks: "EFT cleared transaction reference TXN99420.",
    recordStatus: "Paid",
    createdBy: "rahul.sales@arvicon.com",
    updatedBy: "neha.finance@arvicon.com",
    lastUpdatedTimestamp: "2026-05-20T16:00:00Z"
  },
  {
    id: "TADA-2026-00002",
    timestamp: "2026-05-22T08:15:00Z",
    employeeName: "Pooja Patel",
    employeeCode: "EMP-2026-068",
    employeeEmail: "pooja.manager@arvicon.com",
    designation: "Area Sales Manager",
    state: "Gujarat",
    department: "Sales & Marketing",
    date: "2026-05-21",
    poNo: "PO-88241",
    particulars: "Regional retail evaluation and dealer support across Surat & Baroda main branches.",
    openingReading: 8940,
    closingReading: 9120,
    readingDifference: 180,
    ta: 1800,
    da: 900,
    hotel: 2200,
    mobileExp: 200,
    otherExp: 350,
    grandTotal: 5450,
    dispatchedPoNo: "",
    billUploadFileLink: "https://drive.google.com/file/d/1XyT890_TADA_SuratReceipt/view",
    supervisorName: "Vikram Singh",
    supervisorEmail: "vikram.head@arvicon.com",
    supervisorApprovalStatus: "Approved",
    supervisorApprovalDate: "2026-05-23T11:20:00Z",
    supervisorRemarks: "Surat area trip confirmed. Expense claims within state brackets.",
    hrName: "Siddharth Joshi",
    hrEmail: "siddharth.hr@arvicon.com",
    hrApprovalStatus: "Pending",
    hrApprovalDate: "",
    hrRemarks: "",
    accountsPaymentStatus: "Pending",
    paymentDate: "",
    accountsRemarks: "",
    recordStatus: "Pending",
    createdBy: "pooja.manager@arvicon.com",
    updatedBy: "vikram.head@arvicon.com",
    lastUpdatedTimestamp: "2026-05-23T11:20:00Z"
  },
  {
    id: "TADA-2026-00003",
    timestamp: "2026-05-28T16:05:00Z",
    employeeName: "Rahul Sharma",
    employeeCode: "EMP-2026-042",
    employeeEmail: "rahul.sales@arvicon.com",
    designation: "Sales Executive",
    state: "Maharashtra",
    department: "Sales & Marketing",
    date: "2026-05-27",
    poNo: "PO-99410",
    particulars: "Pune dealer visits and secondary marketing dispatch execution support.",
    openingReading: 12515,
    closingReading: 12720,
    readingDifference: 205,
    ta: 2050,
    da: 500,
    hotel: 1500,
    mobileExp: 100,
    otherExp: 0,
    grandTotal: 4150,
    dispatchedPoNo: "",
    billUploadFileLink: "https://drive.google.com/file/d/1bE_TADA_PuneHotelBooking/view",
    supervisorName: "Vikram Singh",
    supervisorEmail: "vikram.head@arvicon.com",
    supervisorApprovalStatus: "Pending",
    supervisorApprovalDate: "",
    supervisorRemarks: "",
    hrName: "Siddharth Joshi",
    hrEmail: "siddharth.hr@arvicon.com",
    hrApprovalStatus: "Pending",
    hrApprovalDate: "",
    hrRemarks: "",
    accountsPaymentStatus: "Pending",
    paymentDate: "",
    accountsRemarks: "",
    recordStatus: "Pending",
    createdBy: "rahul.sales@arvicon.com",
    updatedBy: "rahul.sales@arvicon.com",
    lastUpdatedTimestamp: "2026-05-28T16:05:00Z"
  }
];
